import type { ProductBundle } from "./api";

const PID = "00000000-0000-0000-0000-000000000001";

// Contenido de respaldo (coincide con el seed de supabase/schema.sql).
// El sitio usa esta data solo cuando Supabase aún no está configurado.
export const SEED_BUNDLE: ProductBundle = {
  product: {
    id: PID,
    slug: "esquinero-5-niveles",
    name: "Estante Vertical 5 Niveles",
    headline: "Estante Vertical",
    headline_em: "5 Niveles",
    description:
      "Diseño esquinero en melamina de 15 mm, abierto por ambos lados para una vista limpia desde cualquier ángulo. Cinco bandejas que soportan hasta 30 kg cada una — ideal para libros, plantas, electrónicos o lo que imagines.",
    price: 120,
    old_price: 145,
    currency: "S/",
    active: true,
    sort_order: 0,
    created_at: "",
    updated_at: "",
  },
  images: [
    {
      id: "1",
      product_id: PID,
      url: "/esquinero1.jpg",
      alt: "Estante Vertical 5 Niveles Creativa Melatech — Foto 1",
      sort_order: 0,
    },
    {
      id: "2",
      product_id: PID,
      url: "/esquinero2.jpeg",
      alt: "Estante Vertical 5 Niveles Creativa Melatech — Foto 2",
      sort_order: 1,
    },
    {
      id: "3",
      product_id: PID,
      url: "/esquinero3.jpeg",
      alt: "Estante Vertical 5 Niveles Creativa Melatech — Foto 3",
      sort_order: 2,
    },
    {
      id: "4",
      product_id: PID,
      url: "/esquinero4.jpeg",
      alt: "Estante Vertical 5 Niveles Creativa Melatech — Foto 4",
      sort_order: 3,
    },
  ],
  specs: [
    { id: "s1", product_id: PID, value: "5", label: "Niveles", sort_order: 0 },
    {
      id: "s2",
      product_id: PID,
      value: "1.75m",
      label: "Altura total",
      sort_order: 1,
    },
    {
      id: "s3",
      product_id: PID,
      value: "30 kg",
      label: "Por bandeja",
      sort_order: 2,
    },
    {
      id: "s4",
      product_id: PID,
      value: "15mm",
      label: "Tablero melamina",
      sort_order: 3,
    },
    {
      id: "s5",
      product_id: PID,
      value: "6/sem",
      label: "Unidades disponibles",
      sort_order: 4,
    },
  ],
  dimensions: [
    {
      id: "d1",
      product_id: PID,
      name: "Alto total",
      value: "1750",
      unit: "mm",
      sort_order: 0,
    },
    {
      id: "d2",
      product_id: PID,
      name: "Ancho",
      value: "300",
      unit: "mm",
      sort_order: 1,
    },
    {
      id: "d3",
      product_id: PID,
      name: "Profundidad",
      value: "300",
      unit: "mm",
      sort_order: 2,
    },
    {
      id: "d4",
      product_id: PID,
      name: "Separación entre niveles",
      value: "313",
      unit: "mm",
      sort_order: 3,
    },
    {
      id: "d5",
      product_id: PID,
      name: "Número de niveles",
      value: "5",
      unit: "bandejas",
      sort_order: 4,
    },
    {
      id: "d6",
      product_id: PID,
      name: "Carga por bandeja",
      value: "~30",
      unit: "kg",
      sort_order: 5,
    },
  ],
  features: [
    {
      id: "f1",
      product_id: PID,
      icon: "🪟",
      title: "Abierto por ambos lados",
      text: "Sin respaldo ni laterales cerrados. La vista es limpia desde cualquier ángulo, ideal para dividir ambientes o lucir tus objetos favoritos.",
      sort_order: 0,
    },
    {
      id: "f2",
      product_id: PID,
      icon: "💪",
      title: "30 kg por bandeja",
      text: "Cada nivel soporta hasta 30 kilogramos. Puedes poner libros pesados, macetas grandes o equipos sin preocuparte por el hundimiento.",
      sort_order: 1,
    },
    {
      id: "f3",
      product_id: PID,
      icon: "🪵",
      title: "Melamina 15 mm premium",
      text: "Superficie resistente a la humedad, al rayado y fácil de limpiar. El grosor de 15 mm garantiza rigidez sin peso innecesario.",
      sort_order: 2,
    },
    {
      id: "f4",
      product_id: PID,
      icon: "📐",
      title: "Perfil esquinero compacto",
      text: "Solo 30 × 30 cm de huella. Aprovecha los rincones que normalmente quedan vacíos, sin bloquear el paso ni la luz.",
      sort_order: 3,
    },
    {
      id: "f5",
      product_id: PID,
      icon: "🎨",
      title: "Blanco, negro o a tu gusto",
      text: "Los colores estándar son blanco y negro, pero fabricamos en el tono que necesites. Solo coordina el color al hacer tu pedido.",
      sort_order: 4,
    },
    {
      id: "f6",
      product_id: PID,
      icon: "⚡",
      title: "Producción local Huancayo",
      text: "Fabricado en Huancayo por Creativa Melatech. Producimos hasta 6 unidades por semana con control de calidad en cada pieza.",
      sort_order: 5,
    },
  ],
  uses: [
    {
      id: "u1",
      product_id: PID,
      emoji: "📚",
      title: "Librería",
      text: "Organiza tus libros favoritos con estilo y acceso fácil en cualquier habitación",
      sort_order: 0,
    },
    {
      id: "u2",
      product_id: PID,
      emoji: "🌿",
      title: "Plantas & Deco",
      text: "Crea un jardín vertical en tu sala, comedor o dormitorio",
      sort_order: 1,
    },
    {
      id: "u3",
      product_id: PID,
      emoji: "🎮",
      title: "Gaming & Tech",
      text: "Consolas, mandos y accesorios perfectamente ordenados y a la vista",
      sort_order: 2,
    },
    {
      id: "u4",
      product_id: PID,
      emoji: "🏪",
      title: "Local comercial",
      text: "Exhibe productos en tiendas, bodegas o negocios con estilo profesional",
      sort_order: 3,
    },
  ],
  benefits: [
    {
      id: "b1",
      product_id: PID,
      icon: "🚚",
      text: "Envío en Huancayo según tarifa del transportista",
      sort_order: 0,
    },
    {
      id: "b2",
      product_id: PID,
      icon: "📅",
      text: "Fabricación semanal · Entrega coordinada",
      sort_order: 1,
    },
    {
      id: "b3",
      product_id: PID,
      icon: "🤝",
      text: "Acepta contra entrega",
      sort_order: 2,
    },
    {
      id: "b4",
      product_id: PID,
      icon: "💛",
      text: "Yape · Plin · Efectivo",
      sort_order: 3,
    },
  ],
  colors: [
    {
      id: "c1",
      product_id: PID,
      value: "Blanco",
      swatch: "#f5f5f0",
      sort_order: 0,
    },
    {
      id: "c2",
      product_id: PID,
      value: "Negro",
      swatch: "#1a1a1a",
      sort_order: 1,
    },
    {
      id: "c3",
      product_id: PID,
      value: "A pedido",
      swatch: "linear-gradient(135deg, #d4d4d8 0%, #71717a 50%, #18181b 100%)",
      sort_order: 2,
    },
  ],
  settings: {
    whatsapp: { number: "51948349852", display: "948 349 852" },
    payments: ["💛 Yape", "💜 Plin", "💵 Efectivo", "🤝 Contra entrega"],
    trust: ["🚚 Envío en Huancayo", "🛡️ Garantía de calidad", "📐 Melamina 15 mm"],
    brand: { nav: "Creativa Melatech", footer: "Creativa Melatech" },
    ga4: { measurement_id: "" },
    hero: { eyebrow: "Creativa Melatech · Huancayo" },
    bottom_cta: {
      title: "¿Listo para organizar",
      title_em: "tu espacio?",
      subtitle: "Fabricado en Huancayo · Precios finales · Sin letra pequeña",
    },
    seo: {
      title: "Estante Vertical 5 Niveles | Creativa Melatech Huancayo",
      description:
        "Estante esquinero vertical de 5 niveles en melamina 15 mm. Fabricado en Huancayo, envío a toda la ciudad, contra entrega. S/ 120.00.",
      og_image: "/esquinero1.jpg",
    },
  },
};
